# Jekyll configuration

# Site settings
baseurl: "" # edit baseurl to simply '/' if using as your personal page (instead of a project page)
url: # the base hostname & protocol for your site, e.g. http://example.com
short_url:
lang: 'ca'
timezone: Europe/Madrid
google_analytics:
disqus: username


# Site info
name: Adab1ts JAMstack Demo
mobile_name: Adab1ts JAMstack Demo
title: 'Adab1ts JAMstack Demo'
description: "A beautiful demo site built with Jekyll. The story begins here." # Write an awesome description for your new site here. It will appear in your document head meta (for Google search results) and in your feed.xml site description.

logo: /assets/images/logo.png
email: info@adabits.org
tel: '931 234 567'
color: #42bb92
twitter: adab1ts

# Author's info
author: 'Ada Lovelace'
bio: 'Encantadora de números i mare de la programació'
location: 'Barcelona'
author_image: 'lovelace.png'

# Where things are
source: src
destination: build
fonts_path: assets/fonts
images_path: assets/images
scripts_path: assets/scripts
styles_path: assets/styles

# Handling Reading
encoding: "utf-8"
markdown_ext: "md"

# Build settings
#theme: minima
gems:
  - jekyll-feed

# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - README.md

# Conversion
markdown: kramdown
highlighter: rouge

# Outputting
permalink: pretty
#paginate: 5
#paginate_path: "/page:num/"

# Collections
collections:
  c-events:
    permalink: /events/:year/:month/:day/:slug/
    output: true
  s-projectes-cms_jamstack:
  s-projectes-web_estatica_moderna:
  s-projectes-projecte:
  s-nosaltres:
  p-home:
    output: false

# Site defaults frontmatters
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: multi-section
      tipus: page
      categoria: 'lorem ipsum'
      sections: p-lorem-ipsum-project
      cover_imatge: hero13.jpg
      title: "Títol per SEO"
      description: "Descripció per SEO"
      keywords: "Paraules clau separades per comes"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: post
      permalink: /blog/:categories/:year/:month/:day/:slug/
      titol_entrada: 'Títol de la publicació'
      autor: 'Jane Doe'
      date: 2015-02-05 18:42:16 +0200
      tag: blog
      categoria: campanyes
      cover_imatge: social-media.jpg
      descripcio_imatge: 'This is alt text for cover image'
      title: 'Títol per SEO'
      description: 'Descripció per SEO'
      keywords: "Paraules clau separades per comes"
